const itRoles = [
    { value: "software_engineer", label: "Software Engineer" },
    { value: "frontend_developer", label: "Frontend Developer" },
    { value: "backend_developer", label: "Backend Developer" },
    { value: "fullstack_developer", label: "Full Stack Developer" },
    { value: "devops_engineer", label: "DevOps Engineer" },
    { value: "cloud_engineer", label: "Cloud Engineer" },
    { value: "data_engineer", label: "Data Engineer" },
    { value: "data_scientist", label: "Data Scientist" },
    { value: "machine_learning_engineer", label: "Machine Learning Engineer" },
    { value: "ai_engineer", label: "AI Engineer" },
    { value: "cybersecurity_engineer", label: "Cybersecurity Engineer" },
    { value: "penetration_tester", label: "Penetration Tester" },
    { value: "security_analyst", label: "Security Analyst" },
    { value: "database_administrator", label: "Database Administrator" },
    { value: "system_administrator", label: "System Administrator" },
    { value: "network_engineer", label: "Network Engineer" },
    { value: "site_reliability_engineer", label: "Site Reliability Engineer" },
    { value: "qa_engineer", label: "QA Engineer" },
    { value: "test_automation_engineer", label: "Test Automation Engineer" },
    { value: "business_analyst", label: "Business Analyst" },
    { value: "product_manager", label: "Product Manager" },
    { value: "project_manager", label: "Project Manager" },
    { value: "scrum_master", label: "Scrum Master" },
    { value: "ui_ux_designer", label: "UI/UX Designer" },
    { value: "technical_writer", label: "Technical Writer" },
    { value: "it_support_specialist", label: "IT Support Specialist" },
    { value: "help_desk_technician", label: "Help Desk Technician" },
    { value: "embedded_software_engineer", label: "Embedded Software Engineer" },
    { value: "iot_engineer", label: "IoT Engineer" },
    { value: "blockchain_developer", label: "Blockchain Developer" },
    { value: "game_developer", label: "Game Developer" },
    { value: "computer_vision_engineer", label: "Computer Vision Engineer" },
    { value: "bi_engineer", label: "BI Engineer" },
    { value: "it_consultant", label: "IT Consultant" },
    { value: "erp_consultant", label: "ERP Consultant" },
    { value: "sap_consultant", label: "SAP Consultant" },
    { value: "salesforce_developer", label: "Salesforce Developer" },
    { value: "robotics_engineer", label: "Robotics Engineer" },
    { value: "technical_architect", label: "Technical Architect" },
    { value: "software_architect", label: "Software Architect" },
    { value: "big_data_engineer", label: "Big Data Engineer" },
  ];
  
  const skills = [
    { value: "java", label: "Java" },
    { value: "python", label: "Python" },
    { value: "c++", label: "C++" },
    { value: "javascript", label: "JavaScript" },
    { value: "typescript", label: "TypeScript" },
    { value: "react", label: "React" },
    { value: "angular", label: "Angular" },
    { value: "vue", label: "Vue.js" },
    { value: "nodejs", label: "Node.js" },
    { value: "express", label: "Express.js" },
    { value: "django", label: "Django" },
    { value: "flask", label: "Flask" },
    { value: "spring_boot", label: "Spring Boot" },
    { value: "ruby_on_rails", label: "Ruby on Rails" },
    { value: "sql", label: "SQL" },
    { value: "mongodb", label: "MongoDB" },
    { value: "postgresql", label: "PostgreSQL" },
    { value: "mysql", label: "MySQL" },
    { value: "aws", label: "AWS" },
    { value: "azure", label: "Azure" },
    { value: "google_cloud", label: "Google Cloud" },
    { value: "docker", label: "Docker" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "terraform", label: "Terraform" },
    { value: "jenkins", label: "Jenkins" },
    { value: "git", label: "Git" },
    { value: "ci_cd", label: "CI/CD" },
    { value: "linux", label: "Linux" },
    { value: "bash", label: "Bash" },
    { value: "powershell", label: "PowerShell" },
    { value: "networking", label: "Networking" },
    { value: "cybersecurity", label: "Cybersecurity" },
    { value: "penetration_testing", label: "Penetration Testing" },
    { value: "ethical_hacking", label: "Ethical Hacking" },
    { value: "blockchain", label: "Blockchain" },
    { value: "data_science", label: "Data Science" },
    { value: "machine_learning", label: "Machine Learning" },
    { value: "deep_learning", label: "Deep Learning" },
    { value: "nlp", label: "Natural Language Processing (NLP)" },
    { value: "big_data", label: "Big Data" },
    { value: "hadoop", label: "Hadoop" },
    { value: "spark", label: "Apache Spark" },
    { value: "tableau", label: "Tableau" },
    { value: "power_bi", label: "Power BI" },
    { value: "scrum", label: "Scrum" },
    { value: "agile", label: "Agile" },
    { value: "ux_design", label: "UX Design" },
    { value: "ui_design", label: "UI Design" },
    { value: "wireframing", label: "Wireframing" },
    { value: "prototyping", label: "Prototyping" },
    { value: "figma", label: "Figma" },
    { value: "adobe_xd", label: "Adobe XD" },
    { value: "technical_writing", label: "Technical Writing" },
    { value: "erp", label: "ERP" },
    { value: "sap", label: "SAP" },
    { value: "salesforce", label: "Salesforce" },
  ];
  
  export { itRoles, skills };
  